In [1]:
import numpy as np

In [2]:
def nonlin(x,deriv=False): #define a nonlin function
    if deriv==True:
        return x*(1-x)     #sigmoid函数的导数
    return 1/(1+np.exp(-x))

In [3]:
#注：有多少个权重参数矩阵，就说神经网络有多少层
#单层神经网络，更新一组权重参数w
def danceng(X,Y,w):
    for iter in range(1000):
        l0=X
        l1=nonlin(np.dot(l0,w)) #前向传播
        l1_error=Y-l1 #loss值，损失函数
        l1_grad=l1_error*nonlin(l1,True) #反向传播
        w_grad=np.dot(l0.T,l1_grad) #自身梯度乘以上一步传下来的梯度。自身梯度是l0,上一步传下来的梯度是l1_grad
        w=w+w_grad
    return l1   #返回神经网络预测值

In [4]:
#两层神经网络
def liangceng(X,Y,w0,w1):
    for iter in range(100):
        l0=X
        l1=nonlin(np.dot(l0,w0))
        l2=nonlin(np.dot(l1,w1)) #前向传播
        l2_error=Y-l2
        l2_grad=l2_error*nonlin(l2,True)  #反向传播
        l1_error=l2_grad.dot(w1.T) #下一步的梯度乘以本身权重
        l1_grad=l1_error*nonlin(l1,True)
        w1+=l1.T.dot(l2_grad)
        w0+=l0.T.dot(l1_grad)
    return l2

In [5]:
X=np.array([[0,0,1],[1,0,1],[1,1,1]]) #输入输出的值
X

array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [6]:
Y=np.array([[0,0,1]]).T
Y

array([[0],
       [0],
       [1]])

In [7]:
w=2*np.random.random((3,1))-1 
w

array([[-0.47623601],
       [-0.3326648 ],
       [ 0.96290712]])

In [8]:
w0=2*np.random.random((3,3))-1 #保证矩阵维度
w1=2*np.random.random((3,1))-1 

In [9]:
liangceng(X,Y,w0,w1)

array([[ 0.05529763],
       [ 0.15961501],
       [ 0.78444044]])